{{- if not .Values.cloudSync.clusterKeySecretRefName }}
---
apiVersion: v1
data:
  clusterKey: {{ .Values.cloudSync.clusterKey | b64enc | quote }}
kind: Secret
metadata:
  name: thoras-cloud-sync
{{- end }}
