---
apiVersion: v1
kind: Service
metadata:
  name: thoras-worker
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "thoras.resourceLabels" (dict "root" . "component" .Values.thorasWorker.labels) | nindent 4 }}
spec:
  ports:
  - name: http-metrics
    port: {{ .Values.thorasWorker.prometheus.port }}
    protocol: TCP
    targetPort: {{ .Values.thorasWorker.prometheus.port }}
  selector:
    app: thoras-worker
