{{- if .Values.thorasSlmAgent.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: thoras-slm-api
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "thoras.resourceLabels" (dict "root" . "component" .Values.thorasSlmAgent.labels) | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thoras-slm-api
  template:
    metadata:
      labels:
        app: thoras-slm-api
        {{- with include "thoras.componentLabels" (dict "root" $ "component" .Values.thorasSlmAgent.labels) }}
        {{- . | trim | nindent 8 }}
        {{- end }}
      {{- with .Values.thorasSlmAgent.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ .Values.thorasSlmAgent.serviceAccount.name }}
      {{- if and .Values.imageCredentials.imagePullSecretInDeployment .Values.imageCredentials.secretRef }}
      imagePullSecrets:
      - name: {{ .Values.imageCredentials.secretRef }}
      {{- end }}
      containers:
      - image: {{ .Values.imageCredentials.registry }}/thoras-phi4-mini:{{ default .Values.thorasVersion .Values.thorasSlmAgent.imageTag }}
        imagePullPolicy: "{{ .Values.imagePullPolicy }}"
        name: thoras-slm-api
        ports:
        - containerPort: {{ .Values.thorasSlmAgent.containerPort }}
        {{- if .Values.thorasSlmAgent.resources }}
        resources: {{ .Values.thorasSlmAgent.resources | toYaml | nindent 10 }}
        {{- else }}
        resources:
          limits: {{ .Values.thorasSlmAgent.limits | toYaml | nindent 12 }}
          requests: {{ .Values.thorasSlmAgent.requests | toYaml | nindent 12 }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.thorasSlmAgent.useGlobalAffinity }}
        {{- $globalAffinity := .Values.affinity | default dict | deepCopy }}
        {{- $componentAffinity := .Values.thorasSlmAgent.affinity | default dict | deepCopy }}
        {{- $mergedAffinity := mustMerge dict $globalAffinity $componentAffinity }}
        {{- with $mergedAffinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- else }}
        {{- with .Values.thorasSlmAgent.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
{{- end }}
