{{- if .Values.thorasSlmAgent.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: thoras-slm-api
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "thoras.labels" . | nindent 4 }}
    {{- if or (.Values.labels) (.Values.thorasSlmAgent.labels) }}
      {{- mustMerge .Values.thorasSlmAgent.labels .Values.labels | toYaml | nindent 4 }}
    {{- end }}
spec:
  ports:
  - name: http
    port: {{ .Values.thorasSlmAgent.port }}
    protocol: TCP
    targetPort: {{ .Values.thorasSlmAgent.containerPort }}
  selector:
    app: thoras-slm-api
{{- end }}
