---
apiVersion: batch/v1
kind: Job
metadata:
  name: thoras-pre-delete-hook
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "thoras.resourceLabels" (dict "root" . "component" .Values.thorasOperator.labels) | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: {{ .Release.Name }}
      labels: {{- include "thoras.resourceLabels" (dict "root" . "component" .Values.thorasOperator.labels) | nindent 8 }}
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534 # user: nobody
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: {{ .Values.thorasOperator.serviceAccount.name }}
      restartPolicy: OnFailure
      containers:
      - name: thoras-delete-asts
        image: {{ .Values.imageCredentials.registry }}/services:{{ default .Values.thorasVersion .Values.thorasOperator.imageTag }}
        imagePullPolicy: "{{ .Values.imagePullPolicy }}"
        securityContext:
          allowPrivilegeEscalation: false
        command: ["/app/operator", "uninstall"]
        resources: {}
