apiVersion: v1
kind: ConfigMap
metadata:
  name: thoras-operator-system-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "thoras.labels" . | nindent 4 }}
data:
  system-config.yaml: |
    scaling-paused: false
