---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: thoras-tls-certsgen
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade,post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    "helm.sh/hook-weight": "-10"
  labels:
    {{- include "thoras.labels" . | nindent 4 }}
    app.kubernetes.io/component: webhook-certgen
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: thoras-tls-certsgen
subjects:
  - kind: ServiceAccount
    name: thoras-tls-certsgen
    namespace: {{ .Release.Namespace }}
